[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "IEXScoper"
version = "0.1.0"
authors = [
  { name = "Your Name", email = "you@example.com" },
]
description = "My awesome package"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "AGPLv3" }